sudo: false
language: python
python:
  - "2.7"

services:
  - redis-server
  - memcached

env:
  - TOX_ENV=py26-cryptography
  - TOX_ENV=py26-pycrypto
  - TOX_ENV=py27-cryptography
  - TOX_ENV=py27-pycrypto
  - TOX_ENV=py33-cryptography
  - TOX_ENV=py33-pycrypto
  - TOX_ENV=py34-cryptography
  - TOX_ENV=py34-pycrypto
  - TOX_ENV=py35-cryptography
  - TOX_ENV=py35-pycrypto
  - TOX_ENV=pypy-cryptography
  - TOX_ENV=pypy-pycrypto

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install tox
  - pip install coverage

script: tox -e $TOX_ENV

after_success:
  - pip install scrutinizer-ocular codecov
  - ocular
  - codecov

notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/56c9af5a787e8c742f81
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
