language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install coverage

script: nosetests -v --with-coverage --cover-package=wechatpy

after_success:
  - pip install coveralls
  - coveralls


