language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install coverage httmock

script: nosetests -v --with-coverage --cover-package=wechatpy

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular
