language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
  - "nightly"

services:
  - redis-server
  - memcached

env:
  - CRYPTOPKG="cryptography>=0.8.2"
  - CRYPTOPKG="pycrypto>=2.6.1"

install:
  - pip install -r requirements.txt
  - pip install coverage httmock
  - pip install $CRYPTOPKG

script: nosetests -v --with-coverage --cover-package=wechatpy

after_success:
  - pip install scrutinizer-ocular codecov
  - ocular
  - codecov

notifications:
  webhooks:
    urls:
        - https://webhooks.gitter.im/e/56c9af5a787e8c742f81
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
